Optimized regular expressions and addition of Google's re2
Started changing things

Progress keeping commit

Refactoring result

Better naming

With the name "regex.h" our own file occured in include file search path
set before POSIX's "regex.h", which we included from our regex.h for RE
functionality on Linux.

Renaming it to regex-port.h prevented this misadventure.

Primitive processor sports new regexes

And now the goal is to put them everywhere else.

Clean build for mariadb+columnstore

Fix warnings - remove VLA warnings

Fix warnings

I've found ONE justified use of variable length arrays in code so far:

/home/mariadb-SergeyZefirov/work/mariadb/sergueyz/MariaDBEnterprise/storage/columnstore/columnstore/utils/windowfunction/wf_udaf.cpp: In member function ‘virtual bool windowfunction::WF_udaf::dropValues(int64_t, int64_t)’:
/home/mariadb-SergeyZefirov/work/mariadb/sergueyz/MariaDBEnterprise/storage/columnstore/columnstore/utils/windowfunction/wf_udaf.cpp:152:56: warning: variable length array ‘flags’ is used [-Wvla]
         uint32_t flags[getContext().getParameterCount()];

This array is defined inside a loop.

Most probably, getContext().getParameterCount() is bound by some
reasonably big value and it is possible to define it using that value.

Investigating.

Also, there's a lot of "type range" warnings like "x < 0 is always false
for unsigned x". I also need to read code around these warnings and look
whether these comparisons are genuinely needed.

Fix warnings: clean build

Test use of libre2

Fix unnecessary install for libre2

Cmake does not attempt to install it into /usr anymore.

Remove regex zoo - now we use our only regex interface

Got missing symbols in the link stage

Going to investigate.

An idea to test on dev machine

cmake itself (very likely) or CMakeLists.txt in re2 ignore INSTALL_DIR
and our good superhuman StackOverflow intellect suggests direct setting
of INSTALL_DIR_PREFIX.

That strange behavior is 5 years old at this time.

Working installation command

Now to final touch - adding proper libraries, library link, etc.

Now we can use re2 if need to

Revert fixes of warnings

Revert warning fixes

Revert warning fixes

Revert warning fixes

Revert warning fixes

Trying fix for missing libre2.so

Commented two problematic subcomponents

Fix extraneous 'add_library'

Fresh libmarias3

Fix compilation error

libre2 should link now

Fix of incorrect flag used

Trying to save permissions during copy

Figuring out permissions

Rename idb_regex_t to mcs_regex_t

Mark slowdown reasons

Name our libre2 build differently

Better name for a library

Try to get better regexp performance

Fix compile errors

Fix install of libre2

Fight the sigsegv